### ISSUE TITLE
Take in account that for europa.eu sites we use *.pt-pt.po files

### ISSUE THREAD

**Issue by c50** [c50/po-xls-for-Drupal#4]

**Comment by madewild** [comment]
Not sure what changes are needed (if any) because currently it already works by calling

`xls-to-po-drupal pt sources/FuturiumD8TranslationvFusion2.0.xlsx it.po futurium-1.0.0-rc1.pt-pt.po`

Am I right to assume that:
* DGT will send the Excel with column header "pt" (and not "pt-pt")
* The header in the merged (fusion) Excel should therefore remain "pt"
* The "Language-Team" metadata in the PO file should remain "Portuguese\n" (and not "Portuguese (Portugal)")

Also, I couldn't find the option to general all POs files in one go from xls-to-po-drupal, should we develop and additional script for that (and handle the pt-pt issue in there)?

**Comment by madewild** [comment]
Fixed in fututium-translations repo
